# Generated by Django 2.2.19 on 2022-06-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contact',
        ),
    ]
